/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IEarningEngineActivation, IEarningEngineActivationInterface } from "../../ActivationController.sol/IEarningEngineActivation.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "asset",
        "type": "address"
      }
    ],
    "name": "isRegisteredAsset",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "tokenId",
        "type": "uint256"
      },
      {
        "internalType": "address[]",
        "name": "assets",
        "type": "address[]"
      }
    ],
    "name": "onNftActivation",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "tokenId",
        "type": "uint256"
      }
    ],
    "name": "onNftDeactivation",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IEarningEngineActivation__factory {
    static readonly abi = _abi;
    static createInterface(): IEarningEngineActivationInterface {
      return new Interface(_abi) as IEarningEngineActivationInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IEarningEngineActivation {
      return new Contract(address, _abi, runner) as unknown as IEarningEngineActivation;
    }
  }
  