/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../../common.js"
  

  export interface MaliciousReceiverInterface extends Interface {
    getFunction(nameOrSignature: "arm" | "armed" | "attackCount" | "attackData" | "disarm" | "onERC1155BatchReceived" | "onERC1155Received" | "onERC721Received" | "supportsInterface" | "target"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'arm', values: [AddressLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'armed', values?: undefined): string;
encodeFunctionData(functionFragment: 'attackCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'attackData', values?: undefined): string;
encodeFunctionData(functionFragment: 'disarm', values?: undefined): string;
encodeFunctionData(functionFragment: 'onERC1155BatchReceived', values: [AddressLike, AddressLike, BigNumberish[], BigNumberish[], BytesLike]): string;
encodeFunctionData(functionFragment: 'onERC1155Received', values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'onERC721Received', values: [AddressLike, AddressLike, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'target', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'arm', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'armed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'attackCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'attackData', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'disarm', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'onERC1155BatchReceived', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'onERC1155Received', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'onERC721Received', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'target', data: BytesLike): Result;
  }

  

  export interface MaliciousReceiver extends BaseContract {
    
    connect(runner?: ContractRunner | null): MaliciousReceiver;
    waitForDeployment(): Promise<this>;

    interface: MaliciousReceiverInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    arm: TypedContractMethod<
      [_target: AddressLike, _data: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    armed: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    attackCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    attackData: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    disarm: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    onERC1155BatchReceived: TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish[], arg3: BigNumberish[], arg4: BytesLike, ],
      [string],
      'nonpayable'
    >
    

    
    onERC1155Received: TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BigNumberish, arg4: BytesLike, ],
      [string],
      'nonpayable'
    >
    

    
    onERC721Received: TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BytesLike, ],
      [string],
      'nonpayable'
    >
    

    
    supportsInterface: TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    target: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'arm'): TypedContractMethod<
      [_target: AddressLike, _data: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'armed'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'attackCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'attackData'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'disarm'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'onERC1155BatchReceived'): TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish[], arg3: BigNumberish[], arg4: BytesLike, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'onERC1155Received'): TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BigNumberish, arg4: BytesLike, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'onERC721Received'): TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BytesLike, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'target'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    

    filters: {
      
    };
  }