/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../../common.js"
  

  export interface MaliciousTBATargetInterface extends Interface {
    getFunction(nameOrSignature: "arm" | "armed" | "attackAttempts" | "disarm" | "tbaAddress"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'arm', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'armed', values?: undefined): string;
encodeFunctionData(functionFragment: 'attackAttempts', values?: undefined): string;
encodeFunctionData(functionFragment: 'disarm', values?: undefined): string;
encodeFunctionData(functionFragment: 'tbaAddress', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'arm', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'armed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'attackAttempts', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'disarm', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tbaAddress', data: BytesLike): Result;
  }

  

  export interface MaliciousTBATarget extends BaseContract {
    
    connect(runner?: ContractRunner | null): MaliciousTBATarget;
    waitForDeployment(): Promise<this>;

    interface: MaliciousTBATargetInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    arm: TypedContractMethod<
      [_tba: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    armed: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    attackAttempts: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    disarm: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    tbaAddress: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'arm'): TypedContractMethod<
      [_tba: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'armed'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'attackAttempts'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'disarm'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'tbaAddress'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    

    filters: {
      
    };
  }