/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as maliciousTokensSol from './MaliciousTokens.sol/index.js';
export type { maliciousTokensSol };
import type * as testnetRevenueSimulatorSol from './TestnetRevenueSimulator.sol/index.js';
export type { testnetRevenueSimulatorSol };
export type { MockCollectionQ } from './MockCollectionQ.js';
export type { MockERC1155 } from './MockERC1155.js';
export type { MockRevenueToken } from './MockRevenueToken.js';
export type { MockRewardToken } from './MockRewardToken.js';
export type { TestnetPhysicalLiquidityPool } from './TestnetPhysicalLiquidityPool.js';