/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface TestnetPhysicalLiquidityPoolInterface extends Interface {
    getFunction(nameOrSignature: "approveRewardSpender" | "assetRates" | "depositRewardLiquidity" | "getRate" | "getReserve" | "owner" | "renounceOwnership" | "revenueReserves" | "revenueToken" | "rewardReserves" | "setAssetRate" | "swapRevenueForReward" | "totalRevenueSettled" | "totalSwapsExecuted" | "transferOwnership" | "withdrawRevenue" | "withdrawRewardLiquidity"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AssetRateConfigured" | "LiquidityDeposited" | "LiquidityWithdrawn" | "OwnershipTransferred" | "PhysicalSettlementExecuted" | "RevenueWithdrawn"): EventFragment;

    encodeFunctionData(functionFragment: 'approveRewardSpender', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'assetRates', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'depositRewardLiquidity', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getRate', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getReserve', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'revenueReserves', values?: undefined): string;
encodeFunctionData(functionFragment: 'revenueToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'rewardReserves', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setAssetRate', values: [AddressLike, BigNumberish, BigNumberish, BigNumberish, boolean]): string;
encodeFunctionData(functionFragment: 'swapRevenueForReward', values: [AddressLike, BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'totalRevenueSettled', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalSwapsExecuted', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'withdrawRevenue', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'withdrawRewardLiquidity', values: [AddressLike, AddressLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'approveRewardSpender', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'assetRates', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'depositRewardLiquidity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getReserve', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revenueReserves', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revenueToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rewardReserves', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setAssetRate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'swapRevenueForReward', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalRevenueSettled', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalSwapsExecuted', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawRevenue', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawRewardLiquidity', data: BytesLike): Result;
  }

  
    export namespace AssetRateConfiguredEvent {
      export type InputTuple = [asset: AddressLike, numerator: BigNumberish, denominator: BigNumberish, decimals: BigNumberish, isApproved: boolean];
      export type OutputTuple = [asset: string, numerator: bigint, denominator: bigint, decimals: bigint, isApproved: boolean];
      export interface OutputObject {asset: string, numerator: bigint, denominator: bigint, decimals: bigint, isApproved: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace LiquidityDepositedEvent {
      export type InputTuple = [asset: AddressLike, provider: AddressLike, amount: BigNumberish];
      export type OutputTuple = [asset: string, provider: string, amount: bigint];
      export interface OutputObject {asset: string, provider: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace LiquidityWithdrawnEvent {
      export type InputTuple = [asset: AddressLike, recipient: AddressLike, amount: BigNumberish];
      export type OutputTuple = [asset: string, recipient: string, amount: bigint];
      export interface OutputObject {asset: string, recipient: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PhysicalSettlementExecutedEvent {
      export type InputTuple = [asset: AddressLike, sender: AddressLike, recipient: AddressLike, revAmountSpent: BigNumberish, rewardAmountDisbursed: BigNumberish];
      export type OutputTuple = [asset: string, sender: string, recipient: string, revAmountSpent: bigint, rewardAmountDisbursed: bigint];
      export interface OutputObject {asset: string, sender: string, recipient: string, revAmountSpent: bigint, rewardAmountDisbursed: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RevenueWithdrawnEvent {
      export type InputTuple = [recipient: AddressLike, amount: BigNumberish];
      export type OutputTuple = [recipient: string, amount: bigint];
      export interface OutputObject {recipient: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface TestnetPhysicalLiquidityPool extends BaseContract {
    
    connect(runner?: ContractRunner | null): TestnetPhysicalLiquidityPool;
    waitForDeployment(): Promise<this>;

    interface: TestnetPhysicalLiquidityPoolInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    approveRewardSpender: TypedContractMethod<
      [asset: AddressLike, spender: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    assetRates: TypedContractMethod<
      [arg0: AddressLike, ],
      [[bigint, bigint, bigint, boolean] & {numerator: bigint, denominator: bigint, decimals: bigint, isApproved: boolean }],
      'view'
    >
    

    
    depositRewardLiquidity: TypedContractMethod<
      [asset: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getRate: TypedContractMethod<
      [asset: AddressLike, ],
      [[bigint, bigint, bigint, boolean] & {numerator: bigint, denominator: bigint, decimals: bigint, isApproved: boolean }],
      'view'
    >
    

    
    getReserve: TypedContractMethod<
      [asset: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    revenueReserves: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    revenueToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    rewardReserves: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    setAssetRate: TypedContractMethod<
      [asset: AddressLike, numerator: BigNumberish, denominator: BigNumberish, decimals: BigNumberish, isApproved: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    swapRevenueForReward: TypedContractMethod<
      [asset: AddressLike, revAmount: BigNumberish, recipient: AddressLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    totalRevenueSettled: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalSwapsExecuted: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    withdrawRevenue: TypedContractMethod<
      [to: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    withdrawRewardLiquidity: TypedContractMethod<
      [asset: AddressLike, to: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'approveRewardSpender'): TypedContractMethod<
      [asset: AddressLike, spender: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'assetRates'): TypedContractMethod<
      [arg0: AddressLike, ],
      [[bigint, bigint, bigint, boolean] & {numerator: bigint, denominator: bigint, decimals: bigint, isApproved: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'depositRewardLiquidity'): TypedContractMethod<
      [asset: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getRate'): TypedContractMethod<
      [asset: AddressLike, ],
      [[bigint, bigint, bigint, boolean] & {numerator: bigint, denominator: bigint, decimals: bigint, isApproved: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'getReserve'): TypedContractMethod<
      [asset: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revenueReserves'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'revenueToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'rewardReserves'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'setAssetRate'): TypedContractMethod<
      [asset: AddressLike, numerator: BigNumberish, denominator: BigNumberish, decimals: BigNumberish, isApproved: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'swapRevenueForReward'): TypedContractMethod<
      [asset: AddressLike, revAmount: BigNumberish, recipient: AddressLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'totalRevenueSettled'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalSwapsExecuted'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdrawRevenue'): TypedContractMethod<
      [to: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdrawRewardLiquidity'): TypedContractMethod<
      [asset: AddressLike, to: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'AssetRateConfigured'): TypedContractEvent<AssetRateConfiguredEvent.InputTuple, AssetRateConfiguredEvent.OutputTuple, AssetRateConfiguredEvent.OutputObject>;
getEvent(key: 'LiquidityDeposited'): TypedContractEvent<LiquidityDepositedEvent.InputTuple, LiquidityDepositedEvent.OutputTuple, LiquidityDepositedEvent.OutputObject>;
getEvent(key: 'LiquidityWithdrawn'): TypedContractEvent<LiquidityWithdrawnEvent.InputTuple, LiquidityWithdrawnEvent.OutputTuple, LiquidityWithdrawnEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'PhysicalSettlementExecuted'): TypedContractEvent<PhysicalSettlementExecutedEvent.InputTuple, PhysicalSettlementExecutedEvent.OutputTuple, PhysicalSettlementExecutedEvent.OutputObject>;
getEvent(key: 'RevenueWithdrawn'): TypedContractEvent<RevenueWithdrawnEvent.InputTuple, RevenueWithdrawnEvent.OutputTuple, RevenueWithdrawnEvent.OutputObject>;

    filters: {
      
      'AssetRateConfigured(address,uint256,uint256,uint8,bool)': TypedContractEvent<AssetRateConfiguredEvent.InputTuple, AssetRateConfiguredEvent.OutputTuple, AssetRateConfiguredEvent.OutputObject>;
      AssetRateConfigured: TypedContractEvent<AssetRateConfiguredEvent.InputTuple, AssetRateConfiguredEvent.OutputTuple, AssetRateConfiguredEvent.OutputObject>;
    

      'LiquidityDeposited(address,address,uint256)': TypedContractEvent<LiquidityDepositedEvent.InputTuple, LiquidityDepositedEvent.OutputTuple, LiquidityDepositedEvent.OutputObject>;
      LiquidityDeposited: TypedContractEvent<LiquidityDepositedEvent.InputTuple, LiquidityDepositedEvent.OutputTuple, LiquidityDepositedEvent.OutputObject>;
    

      'LiquidityWithdrawn(address,address,uint256)': TypedContractEvent<LiquidityWithdrawnEvent.InputTuple, LiquidityWithdrawnEvent.OutputTuple, LiquidityWithdrawnEvent.OutputObject>;
      LiquidityWithdrawn: TypedContractEvent<LiquidityWithdrawnEvent.InputTuple, LiquidityWithdrawnEvent.OutputTuple, LiquidityWithdrawnEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'PhysicalSettlementExecuted(address,address,address,uint256,uint256)': TypedContractEvent<PhysicalSettlementExecutedEvent.InputTuple, PhysicalSettlementExecutedEvent.OutputTuple, PhysicalSettlementExecutedEvent.OutputObject>;
      PhysicalSettlementExecuted: TypedContractEvent<PhysicalSettlementExecutedEvent.InputTuple, PhysicalSettlementExecutedEvent.OutputTuple, PhysicalSettlementExecutedEvent.OutputObject>;
    

      'RevenueWithdrawn(address,uint256)': TypedContractEvent<RevenueWithdrawnEvent.InputTuple, RevenueWithdrawnEvent.OutputTuple, RevenueWithdrawnEvent.OutputObject>;
      RevenueWithdrawn: TypedContractEvent<RevenueWithdrawnEvent.InputTuple, RevenueWithdrawnEvent.OutputTuple, RevenueWithdrawnEvent.OutputObject>;
    
    };
  }