/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../common.js"
  import type { ERC6551Registry, ERC6551RegistryInterface } from "../../erc6551/ERC6551Registry.js";

  const _abi = [
  {
    "inputs": [],
    "name": "AccountCreationFailed",
    "type": "error"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "internalType": "address",
        "name": "account",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "implementation",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "bytes32",
        "name": "salt",
        "type": "bytes32"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "chainId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "tokenContract",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "tokenId",
        "type": "uint256"
      }
    ],
    "name": "ERC6551AccountCreated",
    "type": "event"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "implementation",
        "type": "address"
      },
      {
        "internalType": "bytes32",
        "name": "salt",
        "type": "bytes32"
      },
      {
        "internalType": "uint256",
        "name": "chainId",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "tokenContract",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "tokenId",
        "type": "uint256"
      }
    ],
    "name": "account",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "implementation",
        "type": "address"
      },
      {
        "internalType": "bytes32",
        "name": "salt",
        "type": "bytes32"
      },
      {
        "internalType": "uint256",
        "name": "chainId",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "tokenContract",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "tokenId",
        "type": "uint256"
      }
    ],
    "name": "createAccount",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  const _bytecode = "0x608060405234801561000f575f80fd5b506103428061001d5f395ff3fe608060405234801561000f575f80fd5b5060043610610034575f3560e01c8063246a0021146100385780638a54c52f14610068575b5f80fd5b610052600480360381019061004d919061026d565b610098565b60405161005f91906102f3565b60405180910390f35b610082600480360381019061007d919061026d565b6100f7565b60405161008f91906102f3565b60405180910390f35b5f60806024608c376e5af43d82803e903d91602b57fd5bf3606c5285605d52733d60ad80600a3d3981f3363d3d373d3d3d363d7360495260ff5f5360b76055206035523060601b6001528460155260555f2060601b60601c5f5260205ff35b5f60806024608c376e5af43d82803e903d91602b57fd5bf3606c5285605d52733d60ad80600a3d3981f3363d3d373d3d3d363d7360495260ff5f5360b76055206035523060601b6001528460155260555f20803b61019b578560b760555ff580610168576320188a595f526004601cfd5b80606c528385897f79f19b3655ee38b1ce526556b7731a20c8f218fbda4a3990b6cc4172fdf887226060606ca46020606cf35b8060601b60601c5f5260205ff35b5f80fd5b5f73ffffffffffffffffffffffffffffffffffffffff82169050919050565b5f6101d6826101ad565b9050919050565b6101e6816101cc565b81146101f0575f80fd5b50565b5f81359050610201816101dd565b92915050565b5f819050919050565b61021981610207565b8114610223575f80fd5b50565b5f8135905061023481610210565b92915050565b5f819050919050565b61024c8161023a565b8114610256575f80fd5b50565b5f8135905061026781610243565b92915050565b5f805f805f60a08688031215610286576102856101a9565b5b5f610293888289016101f3565b95505060206102a488828901610226565b94505060406102b588828901610259565b93505060606102c6888289016101f3565b92505060806102d788828901610259565b9150509295509295909350565b6102ed816101cc565b82525050565b5f6020820190506103065f8301846102e4565b9291505056fea264697066735822122004d8986ca694a98dabe1c74fcc6bad65f8e04995bc3663aa40b520aa8697745a64736f6c63430008180033";

  
      type ERC6551RegistryConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: ERC6551RegistryConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class ERC6551Registry__factory extends ContractFactory {
    
      constructor(...args: ERC6551RegistryConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<ERC6551Registry & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): ERC6551Registry__factory {
      return super.connect(runner) as ERC6551Registry__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): ERC6551RegistryInterface {
      return new Interface(_abi) as ERC6551RegistryInterface;
    }
    
    override attach(address: string | Addressable): ERC6551Registry {
      return super.attach(address) as ERC6551Registry;
    }
  static connect(address: string, runner?: ContractRunner | null): ERC6551Registry {
      return new Contract(address, _abi, runner) as unknown as ERC6551Registry;
    }
  }

  
  