/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../../common.js"
  

  export interface TestnetRevenueSimulatorInterface extends Interface {
    getFunction(nameOrSignature: "acquireRewardAsset" | "conversionRates" | "depositToRewardVault" | "fundRewardVault" | "generateFee" | "owner" | "renounceOwnership" | "revenueToken" | "setConversionRate" | "settleRevenueWithPool" | "totalRevenueCollected" | "totalRevenueConverted" | "totalRewardsAcquired" | "totalRewardsFunded" | "transferOwnership" | "unconvertedRevenue" | "userRevenueContributed" | "withdrawRevenue"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ConversionRateConfigured" | "FeeCollected" | "OwnershipTransferred" | "PhysicalSettlementCompleted" | "RevenueWithdrawn" | "RewardAssetAcquired" | "RewardVaultFunded"): EventFragment;

    encodeFunctionData(functionFragment: 'acquireRewardAsset', values: [AddressLike, BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'conversionRates', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'depositToRewardVault', values: [AddressLike, BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'fundRewardVault', values: [AddressLike, BigNumberish, BigNumberish, AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'generateFee', values: [string, BigNumberish]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'revenueToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'setConversionRate', values: [AddressLike, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'settleRevenueWithPool', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'totalRevenueCollected', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalRevenueConverted', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalRewardsAcquired', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'totalRewardsFunded', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'unconvertedRevenue', values?: undefined): string;
encodeFunctionData(functionFragment: 'userRevenueContributed', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'withdrawRevenue', values: [AddressLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'acquireRewardAsset', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'conversionRates', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'depositToRewardVault', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fundRewardVault', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'generateFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revenueToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setConversionRate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'settleRevenueWithPool', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalRevenueCollected', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalRevenueConverted', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalRewardsAcquired', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalRewardsFunded', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unconvertedRevenue', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'userRevenueContributed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawRevenue', data: BytesLike): Result;
  }

  
    export namespace ConversionRateConfiguredEvent {
      export type InputTuple = [asset: AddressLike, numerator: BigNumberish, denominator: BigNumberish, assetDecimals: BigNumberish];
      export type OutputTuple = [asset: string, numerator: bigint, denominator: bigint, assetDecimals: bigint];
      export interface OutputObject {asset: string, numerator: bigint, denominator: bigint, assetDecimals: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FeeCollectedEvent {
      export type InputTuple = [user: AddressLike, amount: BigNumberish, activity: string];
      export type OutputTuple = [user: string, amount: bigint, activity: string];
      export interface OutputObject {user: string, amount: bigint, activity: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PhysicalSettlementCompletedEvent {
      export type InputTuple = [pool: AddressLike, asset: AddressLike, revenueSpent: BigNumberish, amountAcquired: BigNumberish];
      export type OutputTuple = [pool: string, asset: string, revenueSpent: bigint, amountAcquired: bigint];
      export interface OutputObject {pool: string, asset: string, revenueSpent: bigint, amountAcquired: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RevenueWithdrawnEvent {
      export type InputTuple = [to: AddressLike, amount: BigNumberish];
      export type OutputTuple = [to: string, amount: bigint];
      export interface OutputObject {to: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RewardAssetAcquiredEvent {
      export type InputTuple = [asset: AddressLike, revenueSpent: BigNumberish, amountAcquired: BigNumberish];
      export type OutputTuple = [asset: string, revenueSpent: bigint, amountAcquired: bigint];
      export interface OutputObject {asset: string, revenueSpent: bigint, amountAcquired: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RewardVaultFundedEvent {
      export type InputTuple = [asset: AddressLike, amount: BigNumberish, duration: BigNumberish];
      export type OutputTuple = [asset: string, amount: bigint, duration: bigint];
      export interface OutputObject {asset: string, amount: bigint, duration: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface TestnetRevenueSimulator extends BaseContract {
    
    connect(runner?: ContractRunner | null): TestnetRevenueSimulator;
    waitForDeployment(): Promise<this>;

    interface: TestnetRevenueSimulatorInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    acquireRewardAsset: TypedContractMethod<
      [asset: AddressLike, revenueToSpend: BigNumberish, rewardSource: AddressLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    conversionRates: TypedContractMethod<
      [arg0: AddressLike, ],
      [[bigint, bigint, bigint, boolean] & {rateNumerator: bigint, rateDenominator: bigint, assetDecimals: bigint, isConfigured: boolean }],
      'view'
    >
    

    
    depositToRewardVault: TypedContractMethod<
      [asset: AddressLike, amount: BigNumberish, rewardVaultAddr: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    fundRewardVault: TypedContractMethod<
      [asset: AddressLike, amount: BigNumberish, duration: BigNumberish, earningEngineAddr: AddressLike, rewardVaultAddr: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    generateFee: TypedContractMethod<
      [activity: string, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    revenueToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    setConversionRate: TypedContractMethod<
      [asset: AddressLike, numerator: BigNumberish, denominator: BigNumberish, assetDecimals: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    settleRevenueWithPool: TypedContractMethod<
      [pool: AddressLike, asset: AddressLike, revenueToSpend: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    totalRevenueCollected: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalRevenueConverted: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalRewardsAcquired: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    totalRewardsFunded: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    unconvertedRevenue: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    userRevenueContributed: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    withdrawRevenue: TypedContractMethod<
      [to: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'acquireRewardAsset'): TypedContractMethod<
      [asset: AddressLike, revenueToSpend: BigNumberish, rewardSource: AddressLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'conversionRates'): TypedContractMethod<
      [arg0: AddressLike, ],
      [[bigint, bigint, bigint, boolean] & {rateNumerator: bigint, rateDenominator: bigint, assetDecimals: bigint, isConfigured: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'depositToRewardVault'): TypedContractMethod<
      [asset: AddressLike, amount: BigNumberish, rewardVaultAddr: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'fundRewardVault'): TypedContractMethod<
      [asset: AddressLike, amount: BigNumberish, duration: BigNumberish, earningEngineAddr: AddressLike, rewardVaultAddr: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'generateFee'): TypedContractMethod<
      [activity: string, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revenueToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'setConversionRate'): TypedContractMethod<
      [asset: AddressLike, numerator: BigNumberish, denominator: BigNumberish, assetDecimals: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'settleRevenueWithPool'): TypedContractMethod<
      [pool: AddressLike, asset: AddressLike, revenueToSpend: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'totalRevenueCollected'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalRevenueConverted'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalRewardsAcquired'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalRewardsFunded'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'unconvertedRevenue'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'userRevenueContributed'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'withdrawRevenue'): TypedContractMethod<
      [to: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'ConversionRateConfigured'): TypedContractEvent<ConversionRateConfiguredEvent.InputTuple, ConversionRateConfiguredEvent.OutputTuple, ConversionRateConfiguredEvent.OutputObject>;
getEvent(key: 'FeeCollected'): TypedContractEvent<FeeCollectedEvent.InputTuple, FeeCollectedEvent.OutputTuple, FeeCollectedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'PhysicalSettlementCompleted'): TypedContractEvent<PhysicalSettlementCompletedEvent.InputTuple, PhysicalSettlementCompletedEvent.OutputTuple, PhysicalSettlementCompletedEvent.OutputObject>;
getEvent(key: 'RevenueWithdrawn'): TypedContractEvent<RevenueWithdrawnEvent.InputTuple, RevenueWithdrawnEvent.OutputTuple, RevenueWithdrawnEvent.OutputObject>;
getEvent(key: 'RewardAssetAcquired'): TypedContractEvent<RewardAssetAcquiredEvent.InputTuple, RewardAssetAcquiredEvent.OutputTuple, RewardAssetAcquiredEvent.OutputObject>;
getEvent(key: 'RewardVaultFunded'): TypedContractEvent<RewardVaultFundedEvent.InputTuple, RewardVaultFundedEvent.OutputTuple, RewardVaultFundedEvent.OutputObject>;

    filters: {
      
      'ConversionRateConfigured(address,uint256,uint256,uint8)': TypedContractEvent<ConversionRateConfiguredEvent.InputTuple, ConversionRateConfiguredEvent.OutputTuple, ConversionRateConfiguredEvent.OutputObject>;
      ConversionRateConfigured: TypedContractEvent<ConversionRateConfiguredEvent.InputTuple, ConversionRateConfiguredEvent.OutputTuple, ConversionRateConfiguredEvent.OutputObject>;
    

      'FeeCollected(address,uint256,string)': TypedContractEvent<FeeCollectedEvent.InputTuple, FeeCollectedEvent.OutputTuple, FeeCollectedEvent.OutputObject>;
      FeeCollected: TypedContractEvent<FeeCollectedEvent.InputTuple, FeeCollectedEvent.OutputTuple, FeeCollectedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'PhysicalSettlementCompleted(address,address,uint256,uint256)': TypedContractEvent<PhysicalSettlementCompletedEvent.InputTuple, PhysicalSettlementCompletedEvent.OutputTuple, PhysicalSettlementCompletedEvent.OutputObject>;
      PhysicalSettlementCompleted: TypedContractEvent<PhysicalSettlementCompletedEvent.InputTuple, PhysicalSettlementCompletedEvent.OutputTuple, PhysicalSettlementCompletedEvent.OutputObject>;
    

      'RevenueWithdrawn(address,uint256)': TypedContractEvent<RevenueWithdrawnEvent.InputTuple, RevenueWithdrawnEvent.OutputTuple, RevenueWithdrawnEvent.OutputObject>;
      RevenueWithdrawn: TypedContractEvent<RevenueWithdrawnEvent.InputTuple, RevenueWithdrawnEvent.OutputTuple, RevenueWithdrawnEvent.OutputObject>;
    

      'RewardAssetAcquired(address,uint256,uint256)': TypedContractEvent<RewardAssetAcquiredEvent.InputTuple, RewardAssetAcquiredEvent.OutputTuple, RewardAssetAcquiredEvent.OutputObject>;
      RewardAssetAcquired: TypedContractEvent<RewardAssetAcquiredEvent.InputTuple, RewardAssetAcquiredEvent.OutputTuple, RewardAssetAcquiredEvent.OutputObject>;
    

      'RewardVaultFunded(address,uint256,uint256)': TypedContractEvent<RewardVaultFundedEvent.InputTuple, RewardVaultFundedEvent.OutputTuple, RewardVaultFundedEvent.OutputObject>;
      RewardVaultFunded: TypedContractEvent<RewardVaultFundedEvent.InputTuple, RewardVaultFundedEvent.OutputTuple, RewardVaultFundedEvent.OutputObject>;
    
    };
  }