/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface ActivationControllerInterface extends Interface {
    getFunction(nameOrSignature: "activate" | "activated" | "activatedAt" | "activationCost" | "bananaToken" | "deactivateOnTransfer" | "earningEngine" | "getActivatedAt" | "isActivated" | "oohdiesNFT" | "owner" | "pause" | "paused" | "renounceOwnership" | "requiredPicks" | "setActivationCost" | "setEarningEngine" | "setRequiredPicks" | "totalActivated" | "transferOwnership" | "unpause"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ActivationCostUpdated" | "EarningEngineUpdated" | "NFTActivated" | "NFTDeactivated" | "OwnershipTransferred" | "Paused" | "RequiredPicksUpdated" | "Unpaused"): EventFragment;

    encodeFunctionData(functionFragment: 'activate', values: [BigNumberish, AddressLike[]]): string;
encodeFunctionData(functionFragment: 'activated', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'activatedAt', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'activationCost', values?: undefined): string;
encodeFunctionData(functionFragment: 'bananaToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'deactivateOnTransfer', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'earningEngine', values?: undefined): string;
encodeFunctionData(functionFragment: 'getActivatedAt', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'isActivated', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'oohdiesNFT', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'pause', values?: undefined): string;
encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'requiredPicks', values?: undefined): string;
encodeFunctionData(functionFragment: 'setActivationCost', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setEarningEngine', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setRequiredPicks', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'totalActivated', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'unpause', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'activate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'activated', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'activatedAt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'activationCost', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'bananaToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deactivateOnTransfer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'earningEngine', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getActivatedAt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isActivated', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'oohdiesNFT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'requiredPicks', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setActivationCost', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setEarningEngine', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setRequiredPicks', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalActivated', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unpause', data: BytesLike): Result;
  }

  
    export namespace ActivationCostUpdatedEvent {
      export type InputTuple = [oldCost: BigNumberish, newCost: BigNumberish];
      export type OutputTuple = [oldCost: bigint, newCost: bigint];
      export interface OutputObject {oldCost: bigint, newCost: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EarningEngineUpdatedEvent {
      export type InputTuple = [earningEngine: AddressLike];
      export type OutputTuple = [earningEngine: string];
      export interface OutputObject {earningEngine: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace NFTActivatedEvent {
      export type InputTuple = [tokenId: BigNumberish, owner: AddressLike, bananaBurned: BigNumberish, activatedAtTimestamp: BigNumberish];
      export type OutputTuple = [tokenId: bigint, owner: string, bananaBurned: bigint, activatedAtTimestamp: bigint];
      export interface OutputObject {tokenId: bigint, owner: string, bananaBurned: bigint, activatedAtTimestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace NFTDeactivatedEvent {
      export type InputTuple = [tokenId: BigNumberish, previousOwner: AddressLike];
      export type OutputTuple = [tokenId: bigint, previousOwner: string];
      export interface OutputObject {tokenId: bigint, previousOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RequiredPicksUpdatedEvent {
      export type InputTuple = [oldValue: BigNumberish, newValue: BigNumberish];
      export type OutputTuple = [oldValue: bigint, newValue: bigint];
      export interface OutputObject {oldValue: bigint, newValue: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnpausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ActivationController extends BaseContract {
    
    connect(runner?: ContractRunner | null): ActivationController;
    waitForDeployment(): Promise<this>;

    interface: ActivationControllerInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    activate: TypedContractMethod<
      [tokenId: BigNumberish, assets: AddressLike[], ],
      [void],
      'nonpayable'
    >
    

    
    activated: TypedContractMethod<
      [arg0: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    activatedAt: TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    activationCost: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    bananaToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    deactivateOnTransfer: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    earningEngine: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getActivatedAt: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    isActivated: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    oohdiesNFT: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    pause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    paused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    requiredPicks: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    setActivationCost: TypedContractMethod<
      [newCost: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setEarningEngine: TypedContractMethod<
      [_earningEngine: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setRequiredPicks: TypedContractMethod<
      [newValue: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    totalActivated: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    unpause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'activate'): TypedContractMethod<
      [tokenId: BigNumberish, assets: AddressLike[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'activated'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'activatedAt'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'activationCost'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'bananaToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'deactivateOnTransfer'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'earningEngine'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getActivatedAt'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'isActivated'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'oohdiesNFT'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'paused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'requiredPicks'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'setActivationCost'): TypedContractMethod<
      [newCost: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setEarningEngine'): TypedContractMethod<
      [_earningEngine: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setRequiredPicks'): TypedContractMethod<
      [newValue: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'totalActivated'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'unpause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'ActivationCostUpdated'): TypedContractEvent<ActivationCostUpdatedEvent.InputTuple, ActivationCostUpdatedEvent.OutputTuple, ActivationCostUpdatedEvent.OutputObject>;
getEvent(key: 'EarningEngineUpdated'): TypedContractEvent<EarningEngineUpdatedEvent.InputTuple, EarningEngineUpdatedEvent.OutputTuple, EarningEngineUpdatedEvent.OutputObject>;
getEvent(key: 'NFTActivated'): TypedContractEvent<NFTActivatedEvent.InputTuple, NFTActivatedEvent.OutputTuple, NFTActivatedEvent.OutputObject>;
getEvent(key: 'NFTDeactivated'): TypedContractEvent<NFTDeactivatedEvent.InputTuple, NFTDeactivatedEvent.OutputTuple, NFTDeactivatedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'Paused'): TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
getEvent(key: 'RequiredPicksUpdated'): TypedContractEvent<RequiredPicksUpdatedEvent.InputTuple, RequiredPicksUpdatedEvent.OutputTuple, RequiredPicksUpdatedEvent.OutputObject>;
getEvent(key: 'Unpaused'): TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;

    filters: {
      
      'ActivationCostUpdated(uint256,uint256)': TypedContractEvent<ActivationCostUpdatedEvent.InputTuple, ActivationCostUpdatedEvent.OutputTuple, ActivationCostUpdatedEvent.OutputObject>;
      ActivationCostUpdated: TypedContractEvent<ActivationCostUpdatedEvent.InputTuple, ActivationCostUpdatedEvent.OutputTuple, ActivationCostUpdatedEvent.OutputObject>;
    

      'EarningEngineUpdated(address)': TypedContractEvent<EarningEngineUpdatedEvent.InputTuple, EarningEngineUpdatedEvent.OutputTuple, EarningEngineUpdatedEvent.OutputObject>;
      EarningEngineUpdated: TypedContractEvent<EarningEngineUpdatedEvent.InputTuple, EarningEngineUpdatedEvent.OutputTuple, EarningEngineUpdatedEvent.OutputObject>;
    

      'NFTActivated(uint256,address,uint256,uint256)': TypedContractEvent<NFTActivatedEvent.InputTuple, NFTActivatedEvent.OutputTuple, NFTActivatedEvent.OutputObject>;
      NFTActivated: TypedContractEvent<NFTActivatedEvent.InputTuple, NFTActivatedEvent.OutputTuple, NFTActivatedEvent.OutputObject>;
    

      'NFTDeactivated(uint256,address)': TypedContractEvent<NFTDeactivatedEvent.InputTuple, NFTDeactivatedEvent.OutputTuple, NFTDeactivatedEvent.OutputObject>;
      NFTDeactivated: TypedContractEvent<NFTDeactivatedEvent.InputTuple, NFTDeactivatedEvent.OutputTuple, NFTDeactivatedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'Paused(address)': TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
      Paused: TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
    

      'RequiredPicksUpdated(uint256,uint256)': TypedContractEvent<RequiredPicksUpdatedEvent.InputTuple, RequiredPicksUpdatedEvent.OutputTuple, RequiredPicksUpdatedEvent.OutputObject>;
      RequiredPicksUpdated: TypedContractEvent<RequiredPicksUpdatedEvent.InputTuple, RequiredPicksUpdatedEvent.OutputTuple, RequiredPicksUpdatedEvent.OutputObject>;
    

      'Unpaused(address)': TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
      Unpaused: TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
    
    };
  }