/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface IEarningEngineActivationInterface extends Interface {
    getFunction(nameOrSignature: "isRegisteredAsset" | "onNftActivation" | "onNftDeactivation"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'isRegisteredAsset', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'onNftActivation', values: [BigNumberish, AddressLike[]]): string;
encodeFunctionData(functionFragment: 'onNftDeactivation', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'isRegisteredAsset', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'onNftActivation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'onNftDeactivation', data: BytesLike): Result;
  }

  

  export interface IEarningEngineActivation extends BaseContract {
    
    connect(runner?: ContractRunner | null): IEarningEngineActivation;
    waitForDeployment(): Promise<this>;

    interface: IEarningEngineActivationInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    isRegisteredAsset: TypedContractMethod<
      [asset: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    onNftActivation: TypedContractMethod<
      [tokenId: BigNumberish, assets: AddressLike[], ],
      [void],
      'nonpayable'
    >
    

    
    onNftDeactivation: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'isRegisteredAsset'): TypedContractMethod<
      [asset: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'onNftActivation'): TypedContractMethod<
      [tokenId: BigNumberish, assets: AddressLike[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'onNftDeactivation'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }