/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IEarningEngineFund, IEarningEngineFundInterface } from "../../../mocks/TestnetRevenueSimulator.sol/IEarningEngineFund.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "asset",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "duration",
        "type": "uint256"
      }
    ],
    "name": "fundReward",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IEarningEngineFund__factory {
    static readonly abi = _abi;
    static createInterface(): IEarningEngineFundInterface {
      return new Interface(_abi) as IEarningEngineFundInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IEarningEngineFund {
      return new Contract(address, _abi, runner) as unknown as IEarningEngineFund;
    }
  }
  