/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IMockMinter, IMockMinterInterface } from "../../../mocks/TestnetRevenueSimulator.sol/IMockMinter.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "to",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "mint",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IMockMinter__factory {
    static readonly abi = _abi;
    static createInterface(): IMockMinterInterface {
      return new Interface(_abi) as IMockMinterInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IMockMinter {
      return new Contract(address, _abi, runner) as unknown as IMockMinter;
    }
  }
  