/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IRewardVaultDeposit, IRewardVaultDepositInterface } from "../../../mocks/TestnetRevenueSimulator.sol/IRewardVaultDeposit.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "asset",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "depositReward",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IRewardVaultDeposit__factory {
    static readonly abi = _abi;
    static createInterface(): IRewardVaultDepositInterface {
      return new Interface(_abi) as IRewardVaultDepositInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IRewardVaultDeposit {
      return new Contract(address, _abi, runner) as unknown as IRewardVaultDeposit;
    }
  }
  