/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { ITestnetPhysicalLiquidityPool, ITestnetPhysicalLiquidityPoolInterface } from "../../../mocks/TestnetRevenueSimulator.sol/ITestnetPhysicalLiquidityPool.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "asset",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "revAmount",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "recipient",
        "type": "address"
      }
    ],
    "name": "swapRevenueForReward",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "amountAcquired",
        "type": "uint256"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class ITestnetPhysicalLiquidityPool__factory {
    static readonly abi = _abi;
    static createInterface(): ITestnetPhysicalLiquidityPoolInterface {
      return new Interface(_abi) as ITestnetPhysicalLiquidityPoolInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): ITestnetPhysicalLiquidityPool {
      return new Contract(address, _abi, runner) as unknown as ITestnetPhysicalLiquidityPool;
    }
  }
  