/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'ActivationController', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ActivationController__factory>
getContractFactory(name: 'IBurnableERC20', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IBurnableERC20__factory>
getContractFactory(name: 'IEarningEngineActivation', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IEarningEngineActivation__factory>
getContractFactory(name: 'OohdiesAccount', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.OohdiesAccount__factory>
getContractFactory(name: 'IActivationControllerHook', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IActivationControllerHook__factory>
getContractFactory(name: 'IEarningEngineHook', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IEarningEngineHook__factory>
getContractFactory(name: 'OohdiesNFT', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.OohdiesNFT__factory>
getContractFactory(name: 'IEarningEngineVault', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IEarningEngineVault__factory>
getContractFactory(name: 'RewardVault', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.RewardVault__factory>
getContractFactory(name: 'BananaToken', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.BananaToken__factory>
getContractFactory(name: 'EarningEngine', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.EarningEngine__factory>
getContractFactory(name: 'IActivationControllerView', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IActivationControllerView__factory>
getContractFactory(name: 'MockCollectionQ', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockCollectionQ__factory>
getContractFactory(name: 'MockERC1155', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockERC1155__factory>
getContractFactory(name: 'MockRewardToken', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockRewardToken__factory>
getContractFactory(name: 'IERC6551Account', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IERC6551Account__factory>
getContractFactory(name: 'IERC6551Registry', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IERC6551Registry__factory>
getContractFactory(name: 'ERC6551Registry', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ERC6551Registry__factory>
getContractFactory(name: 'IERC6551Executable', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IERC6551Executable__factory>

  getContractAt(name: 'ActivationController', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ActivationController>
getContractAt(name: 'IBurnableERC20', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IBurnableERC20>
getContractAt(name: 'IEarningEngineActivation', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IEarningEngineActivation>
getContractAt(name: 'OohdiesAccount', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.OohdiesAccount>
getContractAt(name: 'IActivationControllerHook', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IActivationControllerHook>
getContractAt(name: 'IEarningEngineHook', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IEarningEngineHook>
getContractAt(name: 'OohdiesNFT', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.OohdiesNFT>
getContractAt(name: 'IEarningEngineVault', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IEarningEngineVault>
getContractAt(name: 'RewardVault', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.RewardVault>
getContractAt(name: 'BananaToken', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.BananaToken>
getContractAt(name: 'EarningEngine', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.EarningEngine>
getContractAt(name: 'IActivationControllerView', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IActivationControllerView>
getContractAt(name: 'MockCollectionQ', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockCollectionQ>
getContractAt(name: 'MockERC1155', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockERC1155>
getContractAt(name: 'MockRewardToken', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockRewardToken>
getContractAt(name: 'IERC6551Account', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IERC6551Account>
getContractAt(name: 'IERC6551Registry', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IERC6551Registry>
getContractAt(name: 'ERC6551Registry', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ERC6551Registry>
getContractAt(name: 'IERC6551Executable', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IERC6551Executable>

  deployContract(name: 'ActivationController', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ActivationController>
deployContract(name: 'IBurnableERC20', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IBurnableERC20>
deployContract(name: 'IEarningEngineActivation', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IEarningEngineActivation>
deployContract(name: 'OohdiesAccount', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.OohdiesAccount>
deployContract(name: 'IActivationControllerHook', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IActivationControllerHook>
deployContract(name: 'IEarningEngineHook', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IEarningEngineHook>
deployContract(name: 'OohdiesNFT', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.OohdiesNFT>
deployContract(name: 'IEarningEngineVault', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IEarningEngineVault>
deployContract(name: 'RewardVault', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.RewardVault>
deployContract(name: 'BananaToken', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.BananaToken>
deployContract(name: 'EarningEngine', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.EarningEngine>
deployContract(name: 'IActivationControllerView', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IActivationControllerView>
deployContract(name: 'MockCollectionQ', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockCollectionQ>
deployContract(name: 'MockERC1155', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockERC1155>
deployContract(name: 'MockRewardToken', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockRewardToken>
deployContract(name: 'IERC6551Account', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IERC6551Account>
deployContract(name: 'IERC6551Registry', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IERC6551Registry>
deployContract(name: 'ERC6551Registry', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ERC6551Registry>
deployContract(name: 'IERC6551Executable', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IERC6551Executable>

  deployContract(name: 'ActivationController', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ActivationController>
deployContract(name: 'IBurnableERC20', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IBurnableERC20>
deployContract(name: 'IEarningEngineActivation', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IEarningEngineActivation>
deployContract(name: 'OohdiesAccount', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.OohdiesAccount>
deployContract(name: 'IActivationControllerHook', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IActivationControllerHook>
deployContract(name: 'IEarningEngineHook', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IEarningEngineHook>
deployContract(name: 'OohdiesNFT', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.OohdiesNFT>
deployContract(name: 'IEarningEngineVault', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IEarningEngineVault>
deployContract(name: 'RewardVault', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.RewardVault>
deployContract(name: 'BananaToken', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.BananaToken>
deployContract(name: 'EarningEngine', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.EarningEngine>
deployContract(name: 'IActivationControllerView', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IActivationControllerView>
deployContract(name: 'MockCollectionQ', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockCollectionQ>
deployContract(name: 'MockERC1155', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockERC1155>
deployContract(name: 'MockRewardToken', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockRewardToken>
deployContract(name: 'IERC6551Account', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IERC6551Account>
deployContract(name: 'IERC6551Registry', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IERC6551Registry>
deployContract(name: 'ERC6551Registry', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ERC6551Registry>
deployContract(name: 'IERC6551Executable', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IERC6551Executable>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  