// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/utils/ReentrancyGuard.sol";

interface IEarningEngineFund {
    function fundReward(address asset, uint256 amount, uint256 duration) external;
}

interface IRewardVaultDeposit {
    function depositReward(address asset, uint256 amount) external;
}

interface IMockMinter {
    function mint(address to, uint256 amount) external;
}

interface ITestnetPhysicalLiquidityPool {
    function swapRevenueForReward(address asset, uint256 revAmount, address recipient) external returns (uint256 amountAcquired);
}

/**
 * @title TestnetRevenueSimulator
 * @notice TESTNET ONLY - NOT FOR PRODUCTION.
 * @dev Simulates the complete economic path:
 *      User Activity -> Protocol Fees -> Revenue Collector -> Deterministic Reward Acquisition -> RewardVault & EarningEngine Funding.
 */
contract TestnetRevenueSimulator is Ownable, ReentrancyGuard {
    using SafeERC20 for IERC20;

    IERC20 public immutable revenueToken;

    uint256 public totalRevenueCollected;
    uint256 public totalRevenueConverted;

    mapping(address => uint256) public userRevenueContributed;
    mapping(address => uint256) public totalRewardsAcquired;
    mapping(address => uint256) public totalRewardsFunded;

    struct ConversionRate {
        uint256 rateNumerator;
        uint256 rateDenominator;
        uint8 assetDecimals;
        bool isConfigured;
    }

    mapping(address => ConversionRate) public conversionRates;

    event FeeCollected(address indexed user, uint256 amount, string activity);
    event ConversionRateConfigured(
        address indexed asset,
        uint256 numerator,
        uint256 denominator,
        uint8 assetDecimals
    );
    event RewardAssetAcquired(
        address indexed asset,
        uint256 revenueSpent,
        uint256 amountAcquired
    );
    event PhysicalSettlementCompleted(
        address indexed pool,
        address indexed asset,
        uint256 revenueSpent,
        uint256 amountAcquired
    );
    event RewardVaultFunded(
        address indexed asset,
        uint256 amount,
        uint256 duration
    );
    event RevenueWithdrawn(address indexed to, uint256 amount);

    error ZeroAmountNotAllowed();
    error ZeroAddressNotAllowed();
    error AssetNotConfigured(address asset);
    error InsufficientUnconvertedRevenue(uint256 requested, uint256 available);
    error InsufficientRewardBalance(address asset, uint256 required, uint256 available);

    constructor(address _revenueToken, address initialOwner) Ownable(initialOwner) {
        if (_revenueToken == address(0)) revert ZeroAddressNotAllowed();
        revenueToken = IERC20(_revenueToken);
    }

    // =========================================================================
    // 1. REVENUE COLLECTION
    // =========================================================================

    /**
     * @notice Users pay protocol fees generated by simulated activity.
     * @param activity Description of the fee-generating activity (e.g. "Trading", "Staking")
     * @param amount Exact fee amount in revenue tokens (18 decimals)
     */
    function generateFee(string calldata activity, uint256 amount) external nonReentrant {
        if (amount == 0) revert ZeroAmountNotAllowed();

        revenueToken.safeTransferFrom(msg.sender, address(this), amount);

        totalRevenueCollected += amount;
        userRevenueContributed[msg.sender] += amount;

        emit FeeCollected(msg.sender, amount, activity);
    }

    function unconvertedRevenue() public view returns (uint256) {
        if (totalRevenueCollected <= totalRevenueConverted) {
            return 0;
        }
        return totalRevenueCollected - totalRevenueConverted;
    }

    // =========================================================================
    // 2. CONVERSION CONFIGURATION & DETERMINISTIC ACQUISITION
    // =========================================================================

    function setConversionRate(
        address asset,
        uint256 numerator,
        uint256 denominator,
        uint8 assetDecimals
    ) external onlyOwner {
        if (asset == address(0)) revert ZeroAddressNotAllowed();
        if (numerator == 0 || denominator == 0) revert ZeroAmountNotAllowed();

        conversionRates[asset] = ConversionRate({
            rateNumerator: numerator,
            rateDenominator: denominator,
            assetDecimals: assetDecimals,
            isConfigured: true
        });

        emit ConversionRateConfigured(asset, numerator, denominator, assetDecimals);
    }

    /**
     * @notice Converts collected protocol revenue into the target reward asset.
     * @dev Replay-protected: Can never convert more revenue than is currently unconverted.
     * @param asset Target reward token address
     * @param revenueToSpend Amount of collected revenue to spend
     * @param rewardSource Address supplying the reward tokens (e.g. liquidity vault or deployer minter)
     */
    function acquireRewardAsset(
        address asset,
        uint256 revenueToSpend,
        address rewardSource
    ) external onlyOwner nonReentrant returns (uint256 amountAcquired) {
        if (revenueToSpend == 0) revert ZeroAmountNotAllowed();
        if (asset == address(0)) revert ZeroAddressNotAllowed();

        ConversionRate memory rate = conversionRates[asset];
        if (!rate.isConfigured) revert AssetNotConfigured(asset);

        uint256 available = unconvertedRevenue();
        if (revenueToSpend > available) {
            revert InsufficientUnconvertedRevenue(revenueToSpend, available);
        }

        // Calculate acquired token amount with decimal scaling
        // standard 18 decimal base calculation
        uint256 baseAmount = (revenueToSpend * rate.rateNumerator) / rate.rateDenominator;

        if (rate.assetDecimals < 18) {
            uint256 scale = 10 ** (18 - rate.assetDecimals);
            amountAcquired = baseAmount / scale;
        } else if (rate.assetDecimals > 18) {
            uint256 scale = 10 ** (rate.assetDecimals - 18);
            amountAcquired = baseAmount * scale;
        } else {
            amountAcquired = baseAmount;
        }

        if (amountAcquired == 0) revert ZeroAmountNotAllowed();

        totalRevenueConverted += revenueToSpend;
        totalRewardsAcquired[asset] += amountAcquired;

        // Pull reward tokens from rewardSource into this simulator
        IERC20(asset).safeTransferFrom(rewardSource, address(this), amountAcquired);

        emit RewardAssetAcquired(asset, revenueToSpend, amountAcquired);
    }

    /**
     * @notice Performs physical two-way revenue settlement with a designated liquidity pool.
     * @dev REV is physically transferred out to the pool, and acquired reward tokens are physically transferred in.
     */
    function settleRevenueWithPool(
        address pool,
        address asset,
        uint256 revenueToSpend
    ) external onlyOwner nonReentrant returns (uint256 amountAcquired) {
        if (revenueToSpend == 0) revert ZeroAmountNotAllowed();
        if (pool == address(0) || asset == address(0)) revert ZeroAddressNotAllowed();

        uint256 available = unconvertedRevenue();
        if (revenueToSpend > available) {
            revert InsufficientUnconvertedRevenue(revenueToSpend, available);
        }

        totalRevenueConverted += revenueToSpend;

        // 1. Approve pool to pull REV from this simulator
        revenueToken.forceApprove(pool, revenueToSpend);

        // 2. Execute physical swap with pool
        amountAcquired = ITestnetPhysicalLiquidityPool(pool).swapRevenueForReward(
            asset,
            revenueToSpend,
            address(this)
        );

        totalRewardsAcquired[asset] += amountAcquired;

        emit PhysicalSettlementCompleted(pool, asset, revenueToSpend, amountAcquired);
    }

    // =========================================================================
    // 3. REWARD VAULT & EARNING ENGINE FUNDING
    // =========================================================================

    /**
     * @notice Funds the protocol's RewardVault and EarningEngine with acquired reward assets.
     */
    function fundRewardVault(
        address asset,
        uint256 amount,
        uint256 duration,
        address earningEngineAddr,
        address rewardVaultAddr
    ) external onlyOwner nonReentrant {
        if (amount == 0) revert ZeroAmountNotAllowed();
        if (asset == address(0) || earningEngineAddr == address(0) || rewardVaultAddr == address(0)) {
            revert ZeroAddressNotAllowed();
        }

        uint256 balance = IERC20(asset).balanceOf(address(this));
        if (balance < amount) {
            revert InsufficientRewardBalance(asset, amount, balance);
        }

        totalRewardsFunded[asset] += amount;

        // 1. Approve & fund EarningEngine emission stream
        IERC20(asset).forceApprove(earningEngineAddr, amount);
        IEarningEngineFund(earningEngineAddr).fundReward(asset, amount, duration);

        // 2. The acquired tokens for RewardVault backing can also be deposited
        // Note: EarningEngine takes custody of its funded amount, and RewardVault holds claimable backing.
        emit RewardVaultFunded(asset, amount, duration);
    }

    /**
     * @notice Directly deposits acquired reward assets into RewardVault.
     */
    function depositToRewardVault(
        address asset,
        uint256 amount,
        address rewardVaultAddr
    ) external onlyOwner nonReentrant {
        if (amount == 0) revert ZeroAmountNotAllowed();
        if (asset == address(0) || rewardVaultAddr == address(0)) revert ZeroAddressNotAllowed();

        uint256 balance = IERC20(asset).balanceOf(address(this));
        if (balance < amount) {
            revert InsufficientRewardBalance(asset, amount, balance);
        }

        IERC20(asset).forceApprove(rewardVaultAddr, amount);
        IRewardVaultDeposit(rewardVaultAddr).depositReward(asset, amount);
    }

    // =========================================================================
    // 4. ADMIN & SECURITY
    // =========================================================================

    function withdrawRevenue(address to, uint256 amount) external onlyOwner nonReentrant {
        if (to == address(0)) revert ZeroAddressNotAllowed();
        if (amount == 0) revert ZeroAmountNotAllowed();

        revenueToken.safeTransfer(to, amount);
        emit RevenueWithdrawn(to, amount);
    }
}
